"""empty message

Revision ID: 3b2aec88aa99
Revises: fc1077c51bde
Create Date: 2023-04-01 02:38:13.520966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b2aec88aa99"
down_revision = "fc1077c51bde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("about_me", schema=None) as batch_op:
        batch_op.add_column(sa.Column("Company", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("DPFile", sa.String(length=500), nullable=True))
        batch_op.alter_column(
            "Availability",
            existing_type=sa.VARCHAR(length=3),
            type_=sa.Integer(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("about_me", schema=None) as batch_op:
        batch_op.alter_column(
            "Availability",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=3),
            existing_nullable=True,
        )
        batch_op.drop_column("DPFile")
        batch_op.drop_column("Company")

    # ### end Alembic commands ###
